name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-web:
    name: Build web assets
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js 20.12.2
        uses: actions/setup-node@v1
        with:
          node-version: '20.12.2'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint and Prettier
        run: npm run lint
      - name: Build web assets
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  # test:
  #   name: Test
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up Node.js 20.12.2
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '20.12.2'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run unit tests
  #       run: npm run test
  # e2e:
  #   name: E2E
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up Node.js 20.12.2
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '20.12.2'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run end-to-end tests
  #       run: npm run test:e2e
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: [build-web]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Vercel Action
        uses: amondnet/vercel-action@v25
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--prod'
